---
language: ruby
cache: bundler
before_install: gem install bundler -v "~> 2.0"

jobs:
  include:
    - rvm: 2.7.1
      gemfile: gemfiles/graphql_1.11.gemfile
      env: GRAPHQL_RUBY_INTERPRETER=yes
    - rvm: 2.7.1
      gemfile: gemfiles/graphql_1.11.gemfile
      env: GRAPHQL_RUBY_INTERPRETER=no
    - rvm: 2.7.1
      gemfile: gemfiles/anycable_1.0.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/graphql_1.10.gemfile
      env: GRAPHQL_RUBY_INTERPRETER=yes
    - rvm: 2.6.6
      gemfile: gemfiles/graphql_1.10.gemfile
      env: GRAPHQL_RUBY_INTERPRETER=no
    - rvm: 2.6.6
      gemfile: gemfiles/anycable_0.6.gemfile
    - rvm: 2.5.8
      gemfile: gemfiles/graphql_1.9.gemfile
